function grfFun = GRF(a,b,c,d,e,f,g,h)%generates your grf function for the specific parameter values you input, in terms of T
%you can evaluate that function then at T values using grfFun(Tval)

grfFun = @grfIntermed;

    function yy = grfIntermed(T)
        r1 = 0;
        r2 = 0;
        r3 = 0;
        r4 = 1;
        yy = 0.0001+(r1*(b*d*f+b*f*g*(a/b*T)+b*d*h+d*e*h*(a/b*T)) ...
            +r2*(a*d*f*(a/b*T)+a*f*g*(a/b*T).^2+c*f*g*(a/b*T).^2 ...
            +a*d*h*(a/b*T))+r3*(b*c*f*(a/b*T)+b*c*h*(a/b*T) ...
            +a*e*h*(a/b*T).^2+c*e*h*(a/b*T).^2)+r4*(a*d*e*(a/b*T).^2 ...
            +b*c*g*(a/b*T).^2+a*e*g*(a/b*T).^3+c*e*g*(a/b*T).^3)) ...
            /(b*d*f+b*f*g*(a/b*T)+b*d*h+d*e*h*(a/b*T)...
            + a*d*f*(a/b*T)+a*f*g*(a/b*T).^2+c*f*g*(a/b*T).^2 ...
            +a*d*h*(a/b*T)+b*c*f*(a/b*T)+b*c*h*(a/b*T)...
            +a*e*h*(a/b*T).^2+c*e*h*(a/b*T).^2+a*d*e*(a/b*T).^2 ...
            +b*c*g*(a/b*T).^2+a*e*g*(a/b*T).^3+c*e*g*(a/b*T).^3);
    end

% gfrFirstDer = @grfIntermed2;
% 


end

